default:
  tags:
    - dtx-iac-runner

include:
  - project: "digitaltechnologytransformation/devops-repositories/dtx-cicd-templates"
    file: "build/dtx-build.yml"
    ref: master
  - project: "digitaltechnologytransformation/devops-repositories/dtx-cicd-templates"
    file: "deploy/dtx-deploy.yml"
    ref: master


variables:
  OPENSHIFT_ENV:
    value: "LOWER"
    description: "Valid Env are LOWER, PROD and DR"
  OPENSHIFT_PROJECT:
    value: "perf-developer-portal"  # Deploy to staging by default
    description: "Valid Projects are: dev-developer-portal, qa-developer-portal, perf-developer-portal, stage-developer-portal, stage-developer-portal, production-developer-portal"
  DEPLOYMENT_CONFIG_NAME:
    value: "toxi-proxy-client"
    description: "Deployment Config name will be used during Docker Image build as well as assigning image to application."
  DOCKER_REPO_NAME:
    value: "developer-portal-release"
    description: "REPO Name will be 'developer-portal-dev' for Dev environment and 'developer-portal-release' for QA/PERF/ST/PROD/DR environments"
  DOCKER_IMAGE_TAG:
    value: "develop"
    description: "To assign the version number to image. For Dev environment, it will be 'PORT-develop' and 'PORT-{TRACKING-TICKET-NUMBER}' for the QA/PERF/ST/PROD/DR images"
  DOCKER_FILE:
    value: "./Dockerfile"
  DRY_RUN_FLAG:
    value: "false"
    description: "Set value to false or true. Openshift deployment will run as dry-run if the value is set to true"


workflow:
  rules:
    - when: always

stages:
  - build
  - deploy

build and push image:
  stage: build
  extends: .build

deploy to openshift:
  stage: deploy
  extends: .deploy
